version: '1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - 27017
    networks:
      - backend-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./db/:/db/

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  backend:
    image: node
    restart: always
    volumes:
      - ./backend/:/home/node/app
    # ports:
    #   - 8082:8082
    networks:
      - backend-network

    depends_on:
      - mongo

  # frontend:
  #   image: node
  #   restart: always
  #   ports:
  #     -

  #   depends_on:
  #     - backend

volumes:
  db:

networks:
  backend-network: